### ISSUE TITLE
protocol-buffer collides with another libraries 

### ISSUE THREAD

**Issue by hellysmile** [noirello/pyorc#10]
Hey @noirello, thanks for the awesome lib

I have found issues, which is really hard:

```python
import aioprometheus  # import protobuf under the hood
import pyorc

with open("./new_data.orc", "wb") as data:
    with pyorc.Writer(data, "struct<col0:int,col1:string>") as writer:
        writer.write((1, "ORC from Python"))
```

will fail in a 2 of different ways randomly

```
[libprotobuf FATAL /Users/runner/runners/2.163.1/work/1/s/deps/orc-1.6.2/build/protobuf_ep-prefix/src/protobuf_ep/src/google/protobuf/message_lite.cc:71] CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of orc.proto.Footer.
Traceback (most recent call last):
  File "crash.py", line 6, in <module>
    writer.write((1, "ORC from Python"))
  File "XXXX/env/lib/python3.7/site-packages/pyorc/writer.py", line 66, in __exit__
    super().close()
RuntimeError: CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of orc.proto.Footer.
Segmentation fault: 11
```

```
python(50048,0x1094b35c0) malloc: *** error for object 0x7f834747a0f8: pointer being freed was not allocated
python(50048,0x1094b35c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Is there any chance that You will be able to take a look on it?

**Comment by noirello** [comment]
I looked around a little and it looks like it's a common problem with Python binary distributions (and libprotobuf in general) to randomly collapse when the same library is loaded more than once.

The best advice that I've found in these cases is to compile both modules from scratch making sure that they use the same version of the shared protobuf library.

That'd be the first thing I would try, but it might be unfeasible in this situation.

**Comment by hellysmile** [comment]
Thanks a lot for quick answer, as for now going to use optional libprotobuf in https://github.com/claws/aioprometheus/pull/42 , which solves my specific case, but not problem in general

**Comment by PeterGss** [comment]
i met the same case,do you solves the problem?

**Comment by dbaxa** [comment]
Hi @noirello I have raised https://github.com/apache/orc/issues/1425 to see if we can get some consistency in the version of protobuf used in Apache orc & the version used in Apache arrow. However, would you be open to patching 

`deps/orc-1.8.1/cmake_modules/ThirdpartyToolchain.cmake` such that the version set it `21.3` as part of the build process ? 

```diff -Nur  deps/orc-1.8.1/cmake_modules/ThirdpartyToolchain.cmake.orig deps/orc-1.8.1/cmake_modules/ThirdpartyToolchain.cmake
--- deps/orc-1.8.1/cmake_modules/ThirdpartyToolchain.cmake.orig	2023-03-01 01:54:15
+++ deps/orc-1.8.1/cmake_modules/ThirdpartyToolchain.cmake	2023-03-01 01:53:50
@@ -14,7 +14,7 @@
 set(SNAPPY_VERSION "1.1.7")
 set(ZLIB_VERSION "1.2.11")
 set(GTEST_VERSION "1.8.0")
-set(PROTOBUF_VERSION "3.5.1")
+set(PROTOBUF_VERSION "21.3")
 set(ZSTD_VERSION "1.5.2")
 
 option(ORC_PREFER_STATIC_PROTOBUF "Prefer static protobuf library, if available" ON)
```

**Comment by noirello** [comment]
TBH, I'm kind of lost about this issue. I'm not sure how Apache Arrow solved it to avoid collision with other protobuf using modules. I'll try to look into it a little bit more.

**Comment by noirello** [comment]
ORC 2.x still has the 3.5.1 as default, but that's no longer compatible with MSVC 17.x and the available windows agents for Azure Pipelines are shipped with that compiler version.

First, I tried to use vcpkg for the ORC dependencies with the latest protobuf version. Although I could build the ORC library, but failed to properly link it to the module.

So I ended up overriding the set protobuf version as @dbaxa recommended in `ThirdpartyToolchain.cmake`, after downloading the ORC source. I picked `3.21.12` which is the latest of the `3.x.y` for C++ protobuf lib. This is what the pyorc `0.11.0` wheels are bundled with.
