### ISSUE TITLE
Unable to write array data type

### ISSUE THREAD

**Issue by fritzb** [noirello/pyorc#12]
I tried writing an array of string, and getting exception below:
```
    with open("/tmp/data.orc", "wb") as data:
        with pyorc.Writer(data, "struct<col0:array<string>>") as writer:
            writer.write((["a:b", "c:d"]))
```

Here is the trace back:

```
Traceback (most recent call last):
  File "/Users/fritzbudiyanto/vagrant/ubuntu/workflows/tasks/mapid_enrichment/app.py", line 120, in <module>
    main()
  File "/Users/fritzbudiyanto/vagrant/ubuntu/workflows/tasks/mapid_enrichment/app.py", line 114, in main
    writer.write((["a:b", "c:d"]))
TypeError: Item ['a:b', 'c:d'] is not an instance of tuple

```

**Comment by noirello** [comment]
You're just missing a comma:
```python3
    with open("/tmp/data.orc", "wb") as data:
        with pyorc.Writer(data, "struct<col0:array<string>>") as writer:
            writer.write((["a:b", "c:d"] , ))
```
Tuples with single element require an extra comma. ( `(6)` vs `(6,)`)

**Comment by fritzb** [comment]
Thanks, it worked. I'm closing the issue.
