### ISSUE TITLE
Missing /etc/localtime

### ISSUE THREAD

**Issue by fritzb** [noirello/pyorc#13]
When I run pyorc inside a docker image, likely with no timezone, it complained with missing timezone. Is there a workaround ? Docker image without local timezone is pretty common.

```
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'Traceback (most recent call last):\n'
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'  File "/usr/local/bin/mapid_enrichment", line 8, in <module>\n'
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'    sys.exit(main())\n'
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/dist-packages/tasks/mapid_enrichment/app.py", line 229, in main\n'
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b"    orc_json = read_orc_in_json(f'{ETL_TEMP_DIR}/{s3_file}')\n"
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/dist-packages/tasks/mapid_enrichment/app.py", line 168, in read_orc_in_json\n'
[2020-06-10 01:39:48,258] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,258] {pod_launcher.py:125} INFO - b'    reader = pyorc.Reader(orc_data)\n'
[2020-06-10 01:39:48,259] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,259] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/dist-packages/pyorc/reader.py", line 67, in __init__\n'
[2020-06-10 01:39:48,259] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,259] {pod_launcher.py:125} INFO - b'    fileo, batch_size, column_indices, column_names, struct_repr, conv\n'
[2020-06-10 01:39:48,259] {logging_mixin.py:112} INFO - [2020-06-10 01:39:48,259] {pod_launcher.py:125} INFO - b"RuntimeError: Can't open /etc/localtime\n"
```

line 67 is at the c++ constructor call:
```
 66         super().__init__(
 67             fileo, batch_size, column_indices, column_names, struct_repr, conv
```

Perhaps, if /etc/localtime is not found, UTC can be assumed.

**Comment by noirello** [comment]
I think the C++ core library for its timestamp implementation relies on having a localtime set.

So far my solution for this, is to add
```
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
```
to the Docker image.
