### ISSUE TITLE
Installation on clean pypy3 environment fails: pybind11 missing

### ISSUE THREAD

**Issue by jruere** [noirello/pyorc#34]
On a clean environment using pypy3 fails for 0.4.0.
It works for 0.3.0.

Dependency on pybind11 is missing.

**Comment by noirello** [comment]
Could you give me some details? Fails how?

**Comment by jruere** [comment]
```
❯ pip install pyorc
Collecting pyorc
  Using cached pyorc-0.4.0.tar.gz (44 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/pypy3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x_7ktqh0/pyorc_a9f89ce1a442430895e50acd7e63d89f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x_7ktqh0/pyorc_a9f89ce1a442430895e50acd7e63d89f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xa4elnot
         cwd: /tmp/pip-install-x_7ktqh0/pyorc_a9f89ce1a442430895e50acd7e63d89f/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x_7ktqh0/pyorc_a9f89ce1a442430895e50acd7e63d89f/setup.py", line 13, in <module>
        from pybind11.setup_helpers import Pybind11Extension, build_ext
    ModuleNotFoundError: No module named 'pybind11'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/57/84/fa84185ddd64f0d687447fc39dcf64efadf1a1648ee09c6f2ac21ee156e3/pyorc-0.4.0.tar.gz#sha256=af56c50dd0545b451a37d38e73e02405f332e91779cf9ab1c8ae3e61b9eb0c90 (from https://pypi.org/simple/pyorc/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyorc-0.3.0.tar.gz (41 kB)
Collecting pybind11>=2.5
  Using cached pybind11-2.6.2-py2.py3-none-any.whl (191 kB)
Building wheels for collected packages: pyorc
  Building wheel for pyorc (setup.py) ... done
  Created wheel for pyorc: filename=pyorc-0.3.0-pp37-pypy37_pp73-linux_x86_64.whl size=581596 sha256=12ff714fedc52e18827a29a2877b38bd1a9f16a0db1f4e633cc5d095a920c86a
  Stored in directory: /home/javier/.cache/pip/wheels/e7/cd/3b/0a19a3333c945ba0b4d2bebc8e31851be92615c786346ee4be
Successfully built pyorc
Installing collected packages: pybind11, pyorc
Successfully installed pybind11-2.6.2 pyorc-0.3.0
```

If I immediately retry, it succeeds to install 0.4.0.

**Comment by noirello** [comment]
Thank you. Which pip version do you use?

Release 0.4.0 uses `pyproject.toml` to define `pybind11` as a setup requirement (instead of the previous `setup.py` `setup_requires` keyword), but it needs a newer pip to handle the `pyproject.toml` (pip 10+).

**Comment by jruere** [comment]
20.something.

**Comment by noirello** [comment]
The new 0.6.0 has prebuild wheels for PyPy3, uploaded to PyPI. Also added a PyPy-based job to the CI pipeline.
